web-server:
  address: "0.0.0.0"
  port: 8181
features:
  enable-redirector: true
  enable-images: false
  enable-text: false
  enable-files: false
  api:
    enable-api: true
    enable-auth: true
    auth-token: ""
    manage-redirectors: true
    manage-images: false
    manage-text: false
    manage-files: false
mongodb: # if uri present, other info ignored
  uri:
  host:
  port: 27017
  use-srv: no
  user:
  pass:
  auth-source: "admin"
  use-auth: yes
  db: "sharex"